name: radio_saphir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  lottie: ^3.1.2
  getwidget: 4.0.0
  google_fonts: 6.2.1
  velocity_x: 4.2.1
  radio_player: ^1.6.0
  line_icons: 2.0.3
  animated_bottom_navigation_bar: 1.3.3
  # flutter_uxcam: ^2.5.4
  wordpress_api: ^1.2.0+1

  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter: 
  assets: 
    - images/
  uses-material-design: true

