name: radio_saphir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 2.2.0
  getwidget: 3.0.1
  google_fonts: 4.0.3
  velocity_x: 3.6.0
  radio_player: 1.2.1
  line_icons: 2.0.1
  animated_bottom_navigation_bar: 1.1.0+1
  wordpress_api: 1.2.0

  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 0.11.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter: 
  assets: 
    - images/
  uses-material-design: true

